### ISSUE TITLE
Nodes won't load on latest ComfyUI Version on Linux

### ISSUE THREAD

**Issue by Kinglord** [tusharbhutt/Endless-Nodes#2]
I'm using the latest ComfyUI (from today) on a clean install with just the Manager node. I'm assuming there's some code here that doesn't like linux for whatever reason? It can't find a folder path.

```
File "/home/oracle/ComfyUI/custom_nodes/Endless-Nodes/endless_nodes.py", line 391, in <module>
    folder_paths.folder_names_and_paths["aesthetic"] = ([os.path.join(folder_paths.models_dir,"aesthetic")], folder_paths.supported_pt_extensions)
                                                                      ^^^^^^^^^^^^
NameError: name 'folder_paths' is not defined
```
Sadly this keeps the entire custom node package from loading, and I didn't even need any of the new scoring stuff :D

Not related - but it also complained about needing colorama as a module, which I fixed manually, but that might need to be added to your requirements file.

**Comment by tusharbhutt** [comment]
Weird! I'll have to have a look to see what's going on

**Comment by tusharbhutt** [comment]
> I'm using the latest ComfyUI (from today) on a clean install with just the Manager node. I'm assuming there's some code here that doesn't like linux for whatever reason? It can't find a folder path.
> 
OK, give it a shot now :)

**Comment by Kinglord** [comment]
It works! Thanks for that super fast fix <3
