### ISSUE TITLE
Totally broke Comfy

### ISSUE THREAD

**Issue by trashie65** [tusharbhutt/Endless-Nodes#5]
After instaling this pack via Comfy Manager Comfy then would not start, i had to uninstall accelerate and transformers and re-install just to get comfy working again... see error message... to scared to try again incase this node pack brakes comfy again
![comfy error](https://github.com/tusharbhutt/Endless-Nodes/assets/45748708/5020ab5a-24da-4d84-81f3-df224a6ffa80)

**Comment by tusharbhutt** [comment]
Was mine the only module you installed at hat time?  I don't see it's name in the list above.

**Comment by trashie65** [comment]
Yes it was the only module,, but i have tried again after reinstalling transformer and accelerate, now i get this error with your module named?

** ComfyUI start up time: 2023-10-08 10:27:52.991574

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'clip']

## Execute install/(de)activation script for 'D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes'
 Collecting clip
   Using cached clip-0.2.0.tar.gz (5.5 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]   
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]   
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\USER\AppData\Local\Temp\pip-install-ox_6fiio\clip_c3cf1d278c954d358109f85d62428611\setup.py", line 4, in <module>
[!]       import clip
[!]   ModuleNotFoundError: No module named 'clip'
[!]   [end of output]
[!]   
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!] 
[!] Encountered error while generating package metadata.
[!] 
[!] See above for output.
[!] 
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.

**Comment by trashie65** [comment]
Yes it was but after reinstalling the two mentioned above i now get this error:

## ComfyUI-Manager: EXECUTE => ['D:\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'clip']

## Execute install/(de)activation script for 'D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes'
 Collecting clip
   Using cached clip-0.2.0.tar.gz (5.5 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]   
[!]   python setup.py egg_info did not run successfully.
[!]   exit code: 1
[!]   
[!]   [6 lines of output]
[!]   Traceback (most recent call last):
[!]     File "<string>", line 2, in <module>
[!]     File "<pip-setuptools-caller>", line 34, in <module>
[!]     File "C:\Users\USER\AppData\Local\Temp\pip-install-ox_6fiio\clip_c3cf1d278c954d358109f85d62428611\setup.py", line 4, in <module>
[!]       import clip
[!]   ModuleNotFoundError: No module named 'clip'
[!]   [end of output]
[!]   
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!] 
[!] Encountered error while generating package metadata.
[!] 
[!] See above for output.
[!] 
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
[!] 
[!] [notice] A new release of pip is available: 23.1.2 -> 23.2.1
[!] [notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
install/(de)activation script failed: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes

**Comment by trashie65** [comment]
Ive just tried agian and i grt the following error:

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes module for custom nodes: No module named 'clip'

what is the module 'clip' and why in is not being found?

**Comment by trashie65** [comment]
Here is the Comfy log incase it helps
[comfyui.log](https://github.com/tusharbhutt/Endless-Nodes/files/12839736/comfyui.log)

**Comment by tusharbhutt** [comment]
CLIP is used for the Aesthetic Scorer and Image Reward nodes.

If you go to the folder where the endless-nodes are and right-click to start up a command prompt, then type the following:

pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git

It may work.  I think I have to update my requirements.txt file

**Comment by trashie65** [comment]
Still getting

ModuleNotFoundError: No module named 'clip'

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes module for custom nodes: No module named 'clip'

**Comment by trashie65** [comment]
Having looked at the other issue report wth clip... https://github.com/tusharbhutt/Endless-Nodes/issues/4 i notice you have given me a different instrution:

If you go to the folder where the endless-nodes are and right-click to start up a command prompt, then type the following:

pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git

The other person you told to:

If you are on a Windows machine (and it seems that you are), navigate to the folder with ComfyUI in it, right-click and open a command prompt. Then type:

pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git

I have tried both ways and still get

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes module for custom nodes: No module named 'clip'

**Comment by trashie65** [comment]
This is what i get after git+https://github.com/openai/CLIP.git

Collecting git+https://github.com/openai/CLIP.git
  Cloning https://github.com/openai/CLIP.git to c:\users\user\appdata\local\temp\pip-req-build-qyf8wup7
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\USER\AppData\Local\Temp\pip-req-build-qyf8wup7'
  Resolved https://github.com/openai/CLIP.git to commit a1d071733d7111c9c014f024669f959182114e33
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ftfy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from clip==1.0) (6.1.1)
Requirement already satisfied: regex in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from clip==1.0) (2023.10.3)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from clip==1.0) (4.66.1)
Requirement already satisfied: torch in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from clip==1.0) (2.1.0)
Requirement already satisfied: torchvision in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from clip==1.0) (0.16.0)
Requirement already satisfied: wcwidth>=0.2.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from ftfy->clip==1.0) (0.2.8)
Requirement already satisfied: filelock in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torch->clip==1.0) (3.12.4)
Requirement already satisfied: typing-extensions in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torch->clip==1.0) (4.8.0)
Requirement already satisfied: sympy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torch->clip==1.0) (1.12)
Requirement already satisfied: networkx in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torch->clip==1.0) (3.1)
Requirement already satisfied: jinja2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torch->clip==1.0) (3.1.2)
Requirement already satisfied: fsspec in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torch->clip==1.0) (2023.9.2)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torchvision->clip==1.0) (1.24.3)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torchvision->clip==1.0) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from torchvision->clip==1.0) (10.0.1)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from tqdm->clip==1.0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch->clip==1.0) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision->clip==1.0) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision->clip==1.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision->clip==1.0) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision->clip==1.0) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch->clip==1.0) (1.3.0)

Looks like all Requirements are already satisfied? so why do i till get the error:

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes module for custom nodes: No module named 'clip'

Very frustrating!!!

**Comment by tusharbhutt** [comment]
It is frustrating.  I'm removing them so you can see the other nodes.

**Comment by tusharbhutt** [comment]
So, in thinking about this some more... my node for the scoring takes parts from [ZaneA's](ComfyUI-Image-Reward) node.  The readme for _that_ node has these installation instructions

```
cd custom_nodes
git clone https://github.com/ZaneA/ComfyUI-ImageReward
pip install -r ComfyUI-ImageReward/requirements.txt
````

That _may_ work for you, it did for me a couple of weeks back.  Also, both of our nodes rely on the package called [ImageReward](https://github.com/THUDM/ImageReward).

The readme file for _this_ node that we both rely on has the following install notes:

```
git clone https://github.com/THUDM/ImageReward.git
cd ImageReward

# Install the integrated package `image-reward`
pip install image-reward
```

After that we get four levels deep and if installing ImageReward directly doesn't work, I am currently at a loss for you, but will try to dig some more.  I am assuming you have GIT installed and added to your PATH?  There was an issue on OpenAI's GitHib page for CLIP that [seems similar to yours and that was the answer](https://github.com/openai/CLIP/issues/243) provided by the people who make CLIP themselves.

**Comment by trashie65** [comment]
Here we go again....

ModuleNotFoundError: No module named 'clip'

Cannot import D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageReward module for custom nodes: No module named 'clip'

logfile attached
[comfyui.log](https://github.com/tusharbhutt/Endless-Nodes/files/12840322/comfyui.log)

All i want to use is the Endless Image Saver because i want to use the time date stamp on the saved image. (is it worth all this hassle?)

**Comment by tusharbhutt** [comment]
> Here we go again....

> 
> All i want to use is the Endless Image Saver because i want to use the time date stamp on the saved image. (is it worth all this hassle?)
> 
I'm tying to fix this for you while on vacation; if you think this is a hassle for you, there's no obligation to use the nodes.  

Here's a standalone node for you that[ is just the saver](https://github.com/tusharbhutt/Endless-Nodes/blob/main/RevertSaver.py).

Now... I have to go take care of my sick daughter and try to actually enjoy my vacation instead of fixing bugs. I will not be in touch for at least a week.
